import app.scripts.visualization.visualise_boxpot_of_data
import app.scripts.visualization.visualise_corr_of_data
import app.scripts.visualization.visualise_hist_of_data
import app.scripts.visualization.visualise_plot_data
import app.scripts.visualization.visualise_violinplot_data
import app.scripts.visualization.visualize_rolling_avarege_of_data
import app.scripts.visualization.visualize_rolling_statistics_of_data
