import app.scripts.visualization.visualise_boxplot_of_data
import app.scripts.visualization.visualise_corrheatmap_of_data
import app.scripts.visualization.visualise_hist_of_data
import app.scripts.visualization.visualise_plot_of_data
import app.scripts.visualization.visualise_violinplot_of_data
import app.scripts.visualization.visualize_rolling_average_of_data
import app.scripts.visualization.visualize_rolling_statistics_of_data
